namespace CPMS.Models
{
    /// <summary>
    /// Class <c>ReportInfoModel</c> represents the model of the reports generated by the administrator.
    /// </summary>
    public class ReportInfoModel
    {
        public ReviewModel Review;
        public AuthorModel Author;
        public PaperModel Paper;

        /// <summary>
        /// Default constructor.
        /// </summary>
        public ReportInfoModel()
        {
            Review = new ReviewModel();
            Author = new AuthorModel();
            Paper = new PaperModel();
        }
    }
}
